#!/bin/env python

import json
import sys
import time
import datetime
import os

class DailyReading(object):
    def __init__(self, file_name):
        self.json_file = file_name
        try:
            with open(self.json_file, "r") as jf:
                self.schedule = json.load(jf)
        except IOError as ioe:
            sys.stderr.write("Couldn't open {}:\n{}: {}".format(
                self.json_file, ioe.errno, ioe.message))

    def todays_date(self):
        now = datetime.datetime.now()
        return "{}-{}-{}".format(now.year, now.month, now.day)

    def day_of_year(self):
        return int(time.strftime("%j"))

    def print_passages(self):
        info = self.schedule.get("info")
        date_string = self.todays_date()
        hbar_length = len(info) + len(date_string) + 4

        message = "{} -- {}\n{}\n{}\n".format(
            self.schedule.get("info"),
            self.todays_date(),
            "=" * hbar_length,
            ", ".join(self.schedule.get("data2")[self.day_of_year() - 1]))

        sys.stdout.writelines(message)

if __name__ == "__main__":
    from optparse import OptionParser
    prsr = OptionParser()
    prsr.add_option("-p", "--plan", dest="json_file",
                    help="Reading plan; FILE in json format", metavar="FILE")

    (options, args) = prsr.parse_args()
    pasg = DailyReading(options.json_file)
    pasg.print_passages()

