#!/bin/env python3
"""
    Get a daily reading.
    Copyright (C) 2015  K. C. Juntunen

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from daily_reading import *

def main():
    from argparse import ArgumentParser
    #import pysword.pysword
    prsr = ArgumentParser()
    prsr.add_argument("-j", "--json"
                    , dest="json_file",
                    help="Reading plan; FILE in json format"
                    , metavar="FILE")
    prsr.add_argument("-l", "--list", action="store_true",
                    help="Print as a list for redirection or processing.")

    args = prsr.parse_args()
    pasg = DailyReading(args.json_file)
    pl = pasg.get_passages()
    
    if not args.list:
      pasg.print_passages()
    else:
    
      #z = pysword.ZModule("kjv")

      formatted_passage_list = []
      for i in pl:
          book, chapter = i.split()

          if '-' in chapter:
              first, last = chapter.split('-')
              for j in range(int(first), int(last) + 1):
                  formatted_passage_list.append(book + ' ' + str(j))
          else:
              formatted_passage_list.append(book + ' ' + chapter)

      for i in formatted_passage_list:
          book, chapter = i.split()
          verse = 1
          print(i)

if __name__ == "__main__":
  main()