#!/bin/env python3
"""
    Get a daily reading.
    Copyright (C) 2015  K. C. Juntunen

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from daily_reading import *

if __name__ == "__main__":
    from optparse import OptionParser
    prsr = OptionParser()
    prsr.add_option("-p", "--plan"
                    , dest="json_file",
                    help="Reading plan; FILE in json format"
                    , metavar="FILE")

    (options, args) = prsr.parse_args()
    pasg = DailyReading(options.json_file)
    pasg.print_passages()
